INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('KASEY', '123 WINDOW LANE', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'TRIVEX', 'NONE', 'SINGLE VISION', 'KASEY@DOMAIN.COM', '555-555-5555');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('IRELAND', '899 NINTH ST', '2.20', '-0.70', '75', '2.60', '-1.2', '162', '58', 'PLASTIC', 'NONE', 'BIFOCAL', 'IRELAND@DOMAIN.COM', '444-444-4444');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('KIM', '222 FOURTH ST', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'HIGH INDEX', 'NONE', 'BIFOCAL', 'KIM@DOMAIN.COM', '333-333-3333');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('TOM', '555 FIRST COURT', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'PLASTIC', 'NONE', 'SINGLE VISION', 'TOM@DOMAIN.COM', '222-222-2222');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('BOB', '299 TENTH ST', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'PLASTIC', 'NONE', 'SINGLE VISION', 'BOB@DOMAIN.COM', '111-111-1111');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('LUCAS', '882 PARK AVE', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'TRIVEX', 'NONE', 'TRIFOCALS', 'LUCAS@DOMAIN.COM', '777-777-7777');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('JUSTIN', '424 HUNTER LANE', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'TRIVEX', 'NONE', 'SINGLE VISION', 'JUSTIN@DOMAIN.COM', '888-888-8888');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('JEFF', '921 FIRST ST', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'PLASTIC', 'NONE', 'SINGLE VISION', 'JEFF@DOMAIN.COM', '999-999-9999');

INSERT INTO INFO (NAME, ADDRESS, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD, LENS_MATERIAL, LENS_ADDITIONS, LENS_STYLE, EMAIL, PHONE_NUMBER)
VALUES ('TIM', '323 SECOND AVE', '2.10', '-0.80', '80', '2.80', '-1.0', '160', '57', 'HIGH INDEX', 'NONE', 'BIFOCAL', 'TIM@DOMAIN.COM', '000-000-0000');
